### ISSUE TITLE
Stop relying setting RemoveSelfLink=false feature-gate - we're locking it to true with GA graduation in 1.24

### ISSUE THREAD

**Issue by wojtek-t** [k82cn/kube-arbitrator#958]
Upstream Kubernetes is going to get rid of ability to set SelfLink in release 1.24 (basically graduate graduate RemoveSelfLink feature gate to stable - see the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink, for a bit more details).

It seems that kube-batch is still vendoring Kubernetes version that is setting it to false:
https://github.com/kubernetes-sigs/kube-batch/blob/master/vendor/k8s.io/apiserver/pkg/features/kube_features.go#L141

This is one more heads'up to stop relying on it (if you do in any place).

**Comment by warmchang** [comment]
typo: volcano --> kube-batch.

**Comment by wojtek-t** [comment]
Sure - fixed
