### ISSUE TITLE
Archive kube-batch

### ISSUE THREAD

**Issue by Huang-Wei** [k82cn/kube-arbitrator#959]
Ref https://github.com/kubernetes/community/pull/6467#discussion_r806914761, shall we consider archiving kube-batch?

**Comment by ahg-g** [comment]
+1, the project is now active under a different repo, Volcano.

**Comment by ArangoGutierrez** [comment]
+1 
GitHub algorithm just recommended me this repo.

**Comment by lilinji** [comment]
+1

**Comment by k82cn** [comment]
Thanks for your suggestion; but I'd like to keep this project open, I'm going to put more time to enhance it.

> the project is now active under a different repo, Volcano.

They're different projects :) Volcano just leveraged kube-batch as first version of its scheduler.
