### ISSUE TITLE
Update k8s version

### ISSUE THREAD

**Issue by k82cn** [k82cn/kube-arbitrator#961]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

1.12 is end of service, it's better to upgrade k8s version to the latest one :)

**Comment by MaheshMoholkar** [comment]
I would like to work on this issue. But I don't know how to upgrade the k8s. Can you help me with this?

**Comment by k82cn** [comment]
> I would like to work on this issue. But I don't know how to upgrade the k8s. Can you help me with this?

Sure. some tasks in my mind:
  1. update go.mod accordingly
  2. update code if any interface or api changed

**Comment by aivinog1** [comment]
Also, I would like to add to the list from [the previous comment](https://github.com/kubernetes-sigs/kube-batch/issues/961#issuecomment-1179713023): probably we also should update the e2e test and specifically the kind version (to match the latest (if possible 😅) version of the API).

**Comment by k82cn** [comment]
+1, we also need to update the version of those component.

**Comment by MaheshMoholkar** [comment]
I tried but I think I don't have enough skills to handle this issue 🙂

**Comment by aivinog1** [comment]
So, let me handle this then :)

**Comment by MaheshMoholkar** [comment]
Yeah good luck

**Comment by mrbobbytables** [comment]
Repo is to be archived, for more information please see: https://github.com/kubernetes/org/issues/4200

/close
